version: '3.4'

services:
  # portal.web:
  #   image: soa/portal.web
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - authentication.api
  #     - books.api

  authentication.api:
    image: soa/authentication.api
    expose:
      - "3000"
    ports:
      - "3000:3000"

  books.api:
    image: soa/books.api
    expose:
      - "3001"
    ports:
      - "3001:3001"